CREATE TABLE LANGUAGES
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
    	LANGUAGE TEXT);
CREATE TABLE DIRECTION
    	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_FROM INT,
	ID_TO INT);
CREATE TABLE WORDSTABLE
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_LANG INT,
	ID_TYPE INT,
	WORD_DATA TEXT);
CREATE TABLE PRESENTATION
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_DIRECT INT,
	ID_WORD INT,
	ID_TRANSL INT);
INSERT INTO LANGUAGES (LANGUAGE) VALUES ('en');
INSERT INTO LANGUAGES (LANGUAGE) VALUES ('ru');
INSERT INTO LANGUAGES (LANGUAGE) VALUES ('de');

INSERT INTO DIRECTION (ID_FROM, ID_TO) VALUES (2,1);
INSERT INTO DIRECTION (ID_FROM, ID_TO) VALUES (1,2);
