CREATE TABLE IF NOT EXISTS LANGUAGES 
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
    	LANG TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS DIRECTION
    	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_FROM INT,
	ID_TO INT);
CREATE TABLE IF NOT EXISTS WORDSTABLE
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_LANG INT,
	ID_TYPE INT,
	WORD_DATA TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS PRESENTATION
	(ID INTEGER PRIMARY KEY AUTOINCREMENT,
	ID_DIRECT INT,
	ID_WORD INT,
	ID_TRANSL INT);
DELETE FROM LANGUAGES;
INSERT OR IGNORE INTO LANGUAGES (ID, LANG) VALUES (1, 'en');
INSERT OR IGNORE INTO LANGUAGES (ID, LANG) VALUES (2, 'ru');
INSERT OR IGNORE INTO LANGUAGES (ID, LANG) VALUES (3, 'de');
DELETE FROM DIRECTION;
INSERT OR IGNORE INTO DIRECTION (ID, ID_FROM, ID_TO) VALUES (1, 2, 1);
INSERT OR IGNORE INTO DIRECTION (ID, ID_FROM, ID_TO) VALUES (2, 1, 2);
