SELECT PRES.ID, WT1.WORD_DATA as ONE, WT2.WORD_DATA as SECOND 
FROM PRESENTATION as PRES
INNER JOIN WORDSTABLE AS WT1
INNER JOIN WORDSTABLE AS WT2
ON WT1.ID=PRES.ID_WORD and WT2.ID=PRES.ID_TRANSL
WHERE SECOND is 'abstract';
